apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-rbci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-rbci
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-rbci
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-rbci
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-rbci
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-omlv-tenant/status-quarkus-io/statusquarkusio-rbci@sha256:85c4a2e4869562f996d3e8f89cdbf35b528e4a858bab898e4961e5224f72d3c8
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
